spring:
  datasource:
    password: faroltst@123
    url: jdbc:postgresql://192.168.3.3:5432/farol-teste
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
